spring:
  cloud:
    config:
      server:
        git:
          uri: https://git@github.com:ericksonAssis/config-repo.git
          repos:
            simple: https://git@github.com:ericksonAssis/config-repo.git
            special:
              pattern: special*/dev*,*special*/dev*
              uri: https://git@github.com:ericksonAssis/config-repo.git
            local:
              pattern: local*
              uri: file:/home/erickson/dev/config-repo
