spring:
  cloud:
    config:
      server:
        git:
          uri: https://git@github.com:ericksonAssis/config-repo.git
          repos:
            development:
              pattern:
                - '*/development'
              uri: git@github.com:ericksonAssis/config-repo-development.git
            staging:
              pattern:
                - '*/production'
              uri: https://git@github.com:ericksonAssis/config-repo.git
            local:
              pattern: local*
              uri: file:/home/erickson/dev/config-repo
